# Recommendation System Notebook
- User based recommendation
- User based prediction
- Item based recommendation
- Item based prediction
- Evaluation

In [1]:
# import libraties
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Reading ratings file
# DATASET LINK : https://grouplens.org/datasets/movielens/
ratings = pd.read_csv('ratings.csv', encoding='latin-1')

In [2]:
ratings.head()

userId  movieId  rating   timestamp
0   12882        1     4.0  1147195252
1   12882       32     3.5  1147195307
2   12882       47     5.0  1147195343
3   12882       50     5.0  1147185499
4   12882      110     4.5  1147195239

## Dividing the dataset into train and test

In [3]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(ratings, test_size=0.30, random_state=31)

In [4]:
print(train.shape)
print(test.shape)

(185153, 4)
(79352, 4)


In [5]:
# pivot ratings into movie features
df_movie_features = train.pivot(
    index='userId',
    columns='movieId',
    values='rating'
).fillna(0)

In [6]:
df_movie_features.head()

movieId  1       2       3       4       5       6       7       9       \
userId                                                                    
316         2.5     0.0     0.0     0.0     0.0     0.0     2.0     0.0   
320         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
359         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
370         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
910         0.0     4.0     0.0     0.0     0.0     3.5     0.0     0.0   

movieId  10      11      ...  106487  106489  106782  106920  109374  109487  \
userId                   ...                                                   
316         2.5     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
320         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
359         4.0     4.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
370         0.0     0.0  ...     0.0     3.0     4.5     0.0     0.0     0.0   
910         0.0     4.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  111362  111759  112556  112852  
userId                                   
316         0.0     0.0     0.0     0.0  
320         0.0     0.0     0.0     0.0  
359         0.0     0.0     0.0     0.0  
370         3.0     4.5     3.5     3.0  
910         0.0     4.5     0.0     0.0  

[5 rows x 2500 columns]

### Copy train and test dataset
These dataset will be used for prediction and evaluation. 
- Dummy train will be used later for prediction of the movies which has not been rated by the user. To ignore the movies rated by the user, we will mark it as 0 during prediction. The movies not rated by user is marked as 1 for prediction. 
- Dummy test will be used for evaluation. To evaluate, we will only make prediction on the movies rated by the user. So, this is marked as 1. This is just opposite of dummy_train

In [7]:
dummy_train = train.copy()
dummy_test = test.copy()

In [8]:
dummy_train['rating'] = dummy_train['rating'].apply(lambda x: 0 if x>=1 else 1)
dummy_test['rating'] = dummy_test['rating'].apply(lambda x: 1 if x>=1 else 0)

In [9]:
# The movies not rated by user is marked as 1 for prediction. 
dummy_train = dummy_train.pivot(
    index='userId',
    columns='movieId',
    values='rating'
).fillna(1)

# The movies not rated by user is marked as 0 for evaluation. 
dummy_test = dummy_test.pivot(
    index='userId',
    columns='movieId',
    values='rating'
).fillna(0)

In [10]:
dummy_train.head()

movieId  1       2       3       4       5       6       7       9       \
userId                                                                    
316         0.0     1.0     1.0     1.0     1.0     1.0     0.0     1.0   
320         1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
359         1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
370         1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
910         1.0     0.0     1.0     1.0     1.0     0.0     1.0     1.0   

movieId  10      11      ...  106487  106489  106782  106920  109374  109487  \
userId                   ...                                                   
316         0.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
320         1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
359         0.0     0.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
370         1.0     1.0  ...     1.0     0.0     0.0     1.0     1.0     1.0   
910         1.0     0.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   

movieId  111362  111759  112556  112852  
userId                                   
316         1.0     1.0     1.0     1.0  
320         1.0     1.0     1.0     1.0  
359         1.0     1.0     1.0     1.0  
370         0.0     0.0     0.0     0.0  
910         1.0     0.0     1.0     1.0  

[5 rows x 2500 columns]

In [11]:
dummy_test.head()

movieId  1       2       3       4       5       6       7       9       \
userId                                                                    
316         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
320         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
359         1.0     0.0     0.0     0.0     0.0     1.0     0.0     0.0   
370         1.0     1.0     0.0     0.0     0.0     1.0     0.0     0.0   
910         1.0     0.0     1.0     0.0     1.0     0.0     0.0     0.0   

movieId  10      11      ...  106487  106489  106782  106920  109374  109487  \
userId                   ...                                                   
316         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
320         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
359         0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
370         0.0     0.0  ...     1.0     0.0     0.0     1.0     0.0     0.0   
910         0.0     0.0  ...     0.0     0.0     1.0     0.0     0.0     0.0   

movieId  111362  111759  112556  112852  
userId                                   
316         0.0     0.0     0.0     0.0  
320         0.0     0.0     0.0     0.0  
359         0.0     0.0     0.0     0.0  
370         0.0     0.0     0.0     0.0  
910         0.0     0.0     0.0     0.0  

[5 rows x 2500 columns]

# User Similarity Matrix

## Using Cosine Similarity

In [12]:
from sklearn.metrics.pairwise import pairwise_distances

# User Similarity Matrix
user_correlation = 1 - pairwise_distances(df_movie_features, metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[1.         0.27437326 0.20805722 ... 0.21701259 0.         0.15886221]
 [0.27437326 1.         0.16309164 ... 0.15044338 0.         0.13787661]
 [0.20805722 0.16309164 1.         ... 0.26569469 0.02849447 0.23968733]
 ...
 [0.21701259 0.15044338 0.26569469 ... 1.         0.044708   0.14407477]
 [0.         0.         0.02849447 ... 0.044708   1.         0.0174666 ]
 [0.15886221 0.13787661 0.23968733 ... 0.14407477 0.0174666  1.        ]]


In [13]:
user_correlation.shape

(862, 862)

## Using adjusted Cosine 

### Here, not removing the NaN values and calculating the mean only for the movies rated by the user

In [14]:
movie_features = train.pivot(
    index='userId',
    columns='movieId',
    values='rating'
)

In [15]:
movie_features.head()

movieId  1       2       3       4       5       6       7       9       \
userId                                                                    
316         2.5     NaN     NaN     NaN     NaN     NaN     2.0     NaN   
320         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
359         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
370         NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
910         NaN     4.0     NaN     NaN     NaN     3.5     NaN     NaN   

movieId  10      11      ...  106487  106489  106782  106920  109374  109487  \
userId                   ...                                                   
316         2.5     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
320         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
359         4.0     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
370         NaN     NaN  ...     NaN     3.0     4.5     NaN     NaN     NaN   
910         NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  111362  111759  112556  112852  
userId                                   
316         NaN     NaN     NaN     NaN  
320         NaN     NaN     NaN     NaN  
359         NaN     NaN     NaN     NaN  
370         3.0     4.5     3.5     3.0  
910         NaN     4.5     NaN     NaN  

[5 rows x 2500 columns]

### Normalising the rating of the movie for each user aroung 0 mean

In [16]:
mean = np.nanmean(movie_features, axis=1)
df_subtracted = (movie_features.T-mean).T

In [17]:
df_subtracted.head()

movieId    1         2       3       4       5         6         7       \
userId                                                                    
316     -0.847368       NaN     NaN     NaN     NaN       NaN -1.347368   
320           NaN       NaN     NaN     NaN     NaN       NaN       NaN   
359           NaN       NaN     NaN     NaN     NaN       NaN       NaN   
370           NaN       NaN     NaN     NaN     NaN       NaN       NaN   
910           NaN  0.087607     NaN     NaN     NaN -0.412393       NaN   

movieId  9         10        11      ...  106487    106489    106782  106920  \
userId                               ...                                       
316         NaN -0.847368       NaN  ...     NaN       NaN       NaN     NaN   
320         NaN       NaN       NaN  ...     NaN       NaN       NaN     NaN   
359         NaN  0.315700  0.315700  ...     NaN       NaN       NaN     NaN   
370         NaN       NaN       NaN  ...     NaN -0.790441  0.709559     NaN   
910         NaN       NaN  0.087607  ...     NaN       NaN       NaN     NaN   

movieId  109374  109487    111362    111759    112556    112852  
userId                                                           
316         NaN     NaN       NaN       NaN       NaN       NaN  
320         NaN     NaN       NaN       NaN       NaN       NaN  
359         NaN     NaN       NaN       NaN       NaN       NaN  
370         NaN     NaN -0.790441  0.709559 -0.290441 -0.790441  
910         NaN     NaN       NaN  0.587607       NaN       NaN  

[5 rows x 2500 columns]

### Finding cosine similarity

In [18]:
from sklearn.metrics.pairwise import pairwise_distances

# User Similarity Matrix
user_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[ 1.          0.113453    0.11494838 ...  0.07731154  0.
  -0.04190499]
 [ 0.113453    1.          0.07188267 ...  0.07301337  0.
   0.02765892]
 [ 0.11494838  0.07188267  1.         ...  0.06492798  0.08561282
  -0.01730643]
 ...
 [ 0.07731154  0.07301337  0.06492798 ...  1.          0.05669439
   0.03825774]
 [ 0.          0.          0.08561282 ...  0.05669439  1.
  -0.00102823]
 [-0.04190499  0.02765892 -0.01730643 ...  0.03825774 -0.00102823
   1.        ]]
